namespace: jtdub
name: requests
version: 0.0.4
readme: README.md
authors:
- James Williams <james.williams@networktocode.com>
description: Module for interacting with HTTP services with the python requests library 
tags: ['http', 'https', 'requests', 'uri']
dependencies: {}
repository: http://github.com/jtdub/requests-uri
issues: https://github.com/jtdub/requests-uri/issues 
license_file: LICENSE
