name: PUBLISH TO ANSIBLE GALAXY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: deploy collection to ansible galaxy
      uses: artis3n/ansible_galaxy_collection@v2 
      with:
        api_key: ${{ secrets.GALAXY_KEY }}
